### ISSUE TITLE
Project name consideration

### ISSUE THREAD

**Issue by jcs224** [Octo8080X/plantation#1]
This might not be a big deal, but I just want to make aware the word "plantation" has some stigma in America. Here is an eloquent explanation of the context:

https://qr.ae/pKD6E4

**Comment by Octo8080X** [comment]
@jcs224 san, Thanks for letting me know.
As a non-native English speaker, it was a point I didn't notice because I don't understand it as a context.

The name change is no problem at all.
I also think the sooner you change it, the better.

The name "plantation" was also decided because the module "farm" was registered first.

What should the new name be, planter, garden, or even better, fresh-farm? It's a bit of a quandary.

Any suggestions?

**Comment by jcs224** [comment]
Ah, makes sense. Thanks for your consideration.

Well, as someone who isn't great at coming up with project names :sweat_smile: some ideas would be "Farm-Fresh" or "Garden-Fresh", which is usually used here to describe healthy, organic food delivered directly to customers from the farm or garden! A cute play on words, if you will.

**Comment by Octo8080X** [comment]
Thanks for the advice.

I think I'll go with "Fresh Garden".
There are a number of parts of the type definition that contain "plantation", so I will replace those and complete other actions in the next few days.

**Comment by Octo8080X** [comment]
@jcs224 san.

The project name change went more smoothly than expected.
Thank you very much.

I have also updated the demo site.
https://fresh-garden-demo.deno.dev

**Comment by Octo8080X** [comment]
The project name change is complete, so close this issue.
